version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/weathermap
      - PYTHONPATH=/app
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  tests:
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/weathermap
      - PYTHONPATH=/app
    command: pytest --cov=app --cov-report=term-missing -W ignore::DeprecationWarning
    env_file:
      - .env

volumes:
  mongodb_data:
